# Generated by Django 5.2.10 on 2026-02-24 22:14

import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0002_importjob"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classrolemapping",
            name="unique_class_role_mapping_per_profile",
        ),
        migrations.RemoveConstraint(
            model_name="columnmapping",
            name="unique_column_mapping_per_profile",
        ),
        migrations.RemoveConstraint(
            model_name="devicetypemapping",
            name="unique_device_type_mapping_per_profile",
        ),
        migrations.AlterField(
            model_name="importprofile",
            name="custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterUniqueTogether(
            name="classrolemapping",
            unique_together={("profile", "source_class")},
        ),
        migrations.AlterUniqueTogether(
            name="columnmapping",
            unique_together={("profile", "target_field")},
        ),
        migrations.AlterUniqueTogether(
            name="devicetypemapping",
            unique_together={("profile", "source_make", "source_model")},
        ),
    ]
