# Generated by Django 5.2.10 on 2026-02-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0004_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceExistingMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("source_id", models.CharField(max_length=200)),
                ("netbox_device_id", models.PositiveIntegerField()),
                ("device_name", models.CharField(blank=True, max_length=200)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_matches",
                        to="netbox_data_import.importprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Existing Match",
                "verbose_name_plural": "Device Existing Matches",
                "ordering": ["profile", "source_id"],
                "unique_together": {("profile", "source_id")},
            },
        ),
    ]
