# Generated by Django 5.2.10 on 2026-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0005_deviceexistingmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceexistingmatch",
            name="source_asset_tag",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
