# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 5.2.13 on 2026-04-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0227_alter_interface_speed_bigint"),
        ("netbox_data_import", "0008_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="classrolemapping",
            name="rack_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.racktype"
            ),
        ),
    ]
