# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 5.2.13 on 2026-04-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0009_add_rack_type_to_classrolemapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturermapping",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
