# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 5.2.13 on 2026-05-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0010_alter_manufacturermapping_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="importprofile",
            name="capture_extra_data",
            field=models.BooleanField(default=False),
        ),
    ]
