# Generated by Django 5.2.13 on 2026-05-06 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0012_classrolemapping_rack_type_related_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="columnmapping",
            name="ndi_columnmapping_profile_target",
        ),
    ]
