# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 6.0.4 on 2026-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0013_remove_columnmapping_unique_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="columnmapping",
            name="target_field",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="columntransformrule",
            name="group_1_target",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="columntransformrule",
            name="group_2_target",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
