# Generated by Django 6.0.7 on 2026-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0015_cleanup_duplicate_device_matches"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="deviceexistingmatch",
            constraint=models.UniqueConstraint(
                fields=("profile", "netbox_device_id"),
                name="ndi_devicematch_profile_device",
            ),
        ),
    ]
