# Generated by Django 6.0.7 on 2026-08-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0017_native_contact_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredFieldDifference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("source_id", models.CharField(max_length=200)),
                ("netbox_device_id", models.PositiveIntegerField()),
                ("target_field", models.CharField(max_length=100)),
                ("file_snapshot", models.JSONField(default=dict)),
                ("netbox_snapshot", models.JSONField(default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ignored_field_differences",
                        to="netbox_data_import.importprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignored Field Difference",
                "verbose_name_plural": "Ignored Field Differences",
                "ordering": ["profile", "source_id", "target_field"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "source_id", "netbox_device_id", "target_field"),
                        name="ndi_ignored_diff_profile_source_device_field",
                    )
                ],
            },
        ),
    ]
