# Generated by Django 6.0.7 on 2026-08-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0241_nullify_empty_cable_end"),
        ("netbox_data_import", "0018_ignoredfielddifference"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceImportSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("source_id", models.CharField(blank=True, default="", max_length=200)),
                ("extra_columns", models.JSONField(blank=True, default=dict)),
                ("unassigned_ips", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="data_import_source", to="dcim.device"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sources",
                        to="netbox_data_import.importprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Import Source",
                "verbose_name_plural": "Device Import Sources",
                "ordering": ["device"],
                "indexes": [models.Index(fields=["profile", "source_id"], name="netbox_data_profile_ecec8c_idx")],
            },
        ),
    ]
