# Generated by Django 6.0.7 on 2026-08-17 14:52

import logging

from django.db import migrations

logger = logging.getLogger("netbox_data_import.migrations")

CUSTOM_FIELD_NAME = "data_import_source"
BATCH_SIZE = 500


def _payload_dict(payload, key):
    """Return one dict value from a stored payload, or an empty dict."""
    value = payload.get(key)
    return value if isinstance(value, dict) else {}


def move_import_source_to_plugin_table(apps, schema_editor):
    """Copy every stored import payload into DeviceImportSource, then drop the custom field."""
    Device = apps.get_model("dcim", "Device")
    Rack = apps.get_model("dcim", "Rack")
    CustomField = apps.get_model("extras", "CustomField")
    ImportProfile = apps.get_model("netbox_data_import", "ImportProfile")
    DeviceImportSource = apps.get_model("netbox_data_import", "DeviceImportSource")

    profile_ids = set(ImportProfile.objects.values_list("pk", flat=True))
    records = []
    cleared_devices = []
    orphaned = 0

    def flush():
        DeviceImportSource.objects.bulk_create(records, batch_size=BATCH_SIZE)
        Device.objects.bulk_update(cleared_devices, ["custom_field_data"], batch_size=BATCH_SIZE)
        records.clear()
        cleared_devices.clear()

    devices = Device.objects.filter(custom_field_data__has_key=CUSTOM_FIELD_NAME)
    for device in devices.iterator(chunk_size=BATCH_SIZE):
        payload = device.custom_field_data.pop(CUSTOM_FIELD_NAME)
        cleared_devices.append(device)
        profile_id = payload.get("profile_id") if isinstance(payload, dict) else None
        if profile_id in profile_ids:
            records.append(
                DeviceImportSource(
                    device_id=device.pk,
                    profile_id=profile_id,
                    source_id=str(payload.get("source_id") or "")[:200],
                    extra_columns=_payload_dict(payload, "extra"),
                    unassigned_ips=_payload_dict(payload, "_ip"),
                )
            )
        else:
            # The profile is gone, so nothing can use this binding again.
            orphaned += 1
        if len(cleared_devices) >= BATCH_SIZE:
            flush()
    flush()

    # Racks carried the same key even though the custom field only ever covered devices, which
    # made NetBox reject a rack edit with "Unknown field name". Nothing reads it, so drop it.
    cleared_racks = []
    for rack in Rack.objects.filter(custom_field_data__has_key=CUSTOM_FIELD_NAME).iterator(chunk_size=BATCH_SIZE):
        rack.custom_field_data.pop(CUSTOM_FIELD_NAME)
        cleared_racks.append(rack)
        if len(cleared_racks) >= BATCH_SIZE:
            Rack.objects.bulk_update(cleared_racks, ["custom_field_data"], batch_size=BATCH_SIZE)
            cleared_racks.clear()
    Rack.objects.bulk_update(cleared_racks, ["custom_field_data"], batch_size=BATCH_SIZE)

    CustomField.objects.filter(name=CUSTOM_FIELD_NAME).delete()
    if orphaned:
        logger.warning(
            "Dropped %s stored import payload(s) that named a deleted import profile.",
            orphaned,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0241_nullify_empty_cable_end"),
        ("extras", "0140_imageattachment_image_size"),
        ("netbox_data_import", "0019_deviceimportsource"),
    ]

    operations = [
        # The custom field and its data are removed, so this migration does not reverse.
        migrations.RunPython(move_import_source_to_plugin_table, migrations.RunPython.noop),
    ]
