# Generated by Django 6.0.8 on 2026-08-21 20:03

from django.db import migrations, models

# The columns the flat-workbook adapter takes ownership of. Listing them here keeps the migration
# reproducible after the model drops them.
MOVED_COLUMNS = (
    "sheet_name",
    "source_id_column",
    "custom_field_name",
    "update_existing",
    "create_missing_device_types",
    "capture_extra_data",
    "primary_contact_lookup_field",
    "preview_view_mode",
)

ADAPTER_KEY = "flat_workbook"
SETTING_KEY = "primary_contact_lookup_field"
FROZEN_DEFAULT = "email"


def move_columns_into_adapter_config(apps, schema_editor):
    """Stamp the flat_workbook adapter key and copy the device-format columns into adapter_config."""
    ImportProfile = apps.get_model("netbox_data_import", "ImportProfile")
    ContactRole = apps.get_model("tenancy", "ContactRole")
    role_names = dict(ContactRole.objects.values_list("pk", "name"))

    for profile in ImportProfile.objects.all().iterator():
        config = {column: getattr(profile, column) for column in MOVED_COLUMNS}
        # The role reference becomes a natural key so an exported profile stays portable.
        config["primary_contact_role"] = role_names.get(profile.primary_contact_role_id)
        profile.source_adapter = "flat_workbook"
        profile.adapter_config = config
        profile.save(update_fields=["source_adapter", "adapter_config"])


def repair_empty_primary_contact_lookup_field(apps, schema_editor):
    """Replace the two invalid stored lookup values with the default in effect at this release."""
    ImportProfile = apps.get_model("netbox_data_import", "ImportProfile")
    profiles = ImportProfile.objects.filter(source_adapter=ADAPTER_KEY).only("pk", "adapter_config")
    for profile in profiles.iterator():
        config = profile.adapter_config
        if not isinstance(config, dict) or SETTING_KEY not in config:
            continue
        if config[SETTING_KEY] not in ("", None):
            continue
        ImportProfile.objects.filter(pk=profile.pk).update(adapter_config={**config, SETTING_KEY: FROZEN_DEFAULT})


class Migration(migrations.Migration):
    replaces = [
        ("netbox_data_import", "0021_importprofile_adapter_config_and_more"),
        ("netbox_data_import", "0022_migrate_profile_adapter_config"),
        ("netbox_data_import", "0023_drop_moved_profile_columns"),
        ("netbox_data_import", "0024_repair_empty_primary_contact_lookup_field"),
    ]

    dependencies = [
        ("netbox_data_import", "0020_migrate_import_source_custom_field"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importprofile",
            name="adapter_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="importprofile",
            name="source_adapter",
            field=models.CharField(default="flat_workbook", max_length=50),
        ),
        # No reverse callable: a renamed or deleted ContactRole cannot be resolved back to its id.
        migrations.RunPython(move_columns_into_adapter_config),
        migrations.RemoveField(
            model_name="importprofile",
            name="capture_extra_data",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="create_missing_device_types",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="custom_field_name",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="preview_view_mode",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="primary_contact_lookup_field",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="primary_contact_role",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="sheet_name",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="source_id_column",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="update_existing",
        ),
        migrations.RunPython(repair_empty_primary_contact_lookup_field),
    ]
