# Generated by Django 6.0.8 on 2026-08-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0020_migrate_import_source_custom_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="importprofile",
            name="adapter_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="importprofile",
            name="source_adapter",
            field=models.CharField(default="flat_workbook", max_length=50),
        ),
    ]
