# Generated by Django 6.0.8 on 2026-08-18 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0022_migrate_profile_adapter_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importprofile",
            name="capture_extra_data",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="create_missing_device_types",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="custom_field_name",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="preview_view_mode",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="primary_contact_lookup_field",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="primary_contact_role",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="sheet_name",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="source_id_column",
        ),
        migrations.RemoveField(
            model_name="importprofile",
            name="update_existing",
        ),
    ]
