# Generated by Django 6.0.8 on 2026-08-18 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0021_importprofile_adapter_config"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImportJob",
            new_name="ImportExecution",
        ),
    ]
