# Generated by Django 6.0.8 on 2026-08-18 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_job_notifications"),
        ("netbox_data_import", "0024_rename_importjob_importexecution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importexecution",
            name="dry_run",
        ),
        migrations.RemoveField(
            model_name="importexecution",
            name="result_rows",
        ),
        migrations.AddField(
            model_name="importexecution",
            name="accepted_plan_fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="applied_changes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="failure_detail",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_execution",
                to="core.job",
            ),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="job_backed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="outcome",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="plan_schema_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importexecution",
            name="selected_units",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importexecution",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_executions",
                to="netbox_data_import.importprofile",
            ),
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("content", models.BinaryField()),
                ("content_fingerprint", models.CharField(max_length=64)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_documents",
                        to="netbox_data_import.importprofile",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Document",
                "verbose_name_plural": "Source Documents",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="importexecution",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_executions",
                to="netbox_data_import.sourcedocument",
            ),
        ),
        migrations.AddConstraint(
            model_name="importexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("profile", "idempotency_key"),
                name="ndi_execution_profile_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(fields=["profile", "content_fingerprint"], name="netbox_data_profile_e2c682_idx"),
        ),
    ]
