# Generated by Django 5.2.16 on 2026-08-24 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0025_remove_importexecution_dry_run_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedocument",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_documents",
                to="netbox_data_import.importprofile",
            ),
        ),
    ]
