# Generated by Django 6.0.2 on 2026-08-31 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_job_notifications"),
        ("netbox_data_import", "0026_alter_sourcedocument_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CableClassMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cable_class", models.CharField(max_length=200)),
                ("cable_type_resolved", models.BooleanField(default=False)),
                ("cable_type", models.CharField(blank=True, max_length=50, null=True)),
                ("cable_profile_resolved", models.BooleanField(default=False)),
                ("cable_profile", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cable_class_mappings",
                        to="netbox_data_import.importprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "CableClass Mapping",
                "verbose_name_plural": "CableClass Mappings",
                "ordering": ["profile", "cable_class"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "cable_class"), name="ndi_cableclassmapping_profile_class"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TerminationResolution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("task_type", models.CharField(max_length=50)),
                ("field_key", models.TextField()),
                ("selected_object_id", models.PositiveBigIntegerField()),
                ("selected_display_name", models.CharField(max_length=200)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termination_resolutions",
                        to="netbox_data_import.importprofile",
                    ),
                ),
                (
                    "selected_object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.objecttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Termination Resolution",
                "verbose_name_plural": "Termination Resolutions",
                "ordering": ["profile", "task_type", "field_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "task_type", "field_key"), name="ndi_termresolution_profile_task_key"
                    )
                ],
            },
        ),
    ]
