# Generated by Django 6.0.2 on 2026-09-02 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0241_nullify_empty_cable_end"),
        ("netbox_data_import", "0027_cableclassmapping_terminationresolution"),
    ]

    operations = [
        migrations.CreateModel(
            name="CableImportSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("trace_identity", models.TextField()),
                ("trace_key", models.CharField(editable=False, max_length=64)),
                ("segment_index", models.PositiveIntegerField()),
                ("from_text", models.CharField(blank=True, default="", max_length=500)),
                ("to_text", models.CharField(blank=True, default="", max_length=500)),
                ("direction", models.CharField(blank=True, default="", max_length=20)),
                ("workbook_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("sheet", models.CharField(blank=True, default="", max_length=100)),
                ("block_ordinal", models.PositiveIntegerField(blank=True, null=True)),
                ("row_start", models.PositiveIntegerField(blank=True, null=True)),
                ("row_end", models.PositiveIntegerField(blank=True, null=True)),
                ("export_timestamp", models.CharField(blank=True, default="", max_length=100)),
                (
                    "cable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="data_import_sources", to="dcim.cable"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cable_sources",
                        to="netbox_data_import.importprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cable Import Source",
                "verbose_name_plural": "Cable Import Sources",
                "ordering": ["cable", "profile", "trace_identity"],
                "indexes": [models.Index(fields=["profile", "trace_key"], name="netbox_data_profile_bd7b62_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cable", "profile", "trace_key"), name="ndi_cableimportsource_cable_profile_trace"
                    )
                ],
            },
        ),
    ]
