# Generated by Django 6.0.2 on 2026-09-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0028_cableimportsource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cableimportsource",
            name="from_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="cableimportsource",
            name="to_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
