# Generated by Django 6.1 on 2026-09-05 21:12

import netbox.models.deletion
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0144_customfield_status"),
        ("netbox_data_import", "0030_remove_device_type_creation_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="InferenceBackend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("backend_key", models.SlugField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("adapter_type", models.CharField(default="openai_compatible", max_length=50)),
                ("api_root", models.CharField(max_length=500)),
                ("model", models.CharField(max_length=200)),
                ("authentication", models.CharField(default="bearer", max_length=20)),
                ("response_mode", models.CharField(default="prompt_json", max_length=20)),
                ("credential_reference", models.JSONField()),
                ("connect_timeout", models.PositiveIntegerField(default=5)),
                ("read_timeout", models.PositiveIntegerField(default=60)),
                ("enabled", models.BooleanField(default=False)),
                ("tags", models.ManyToManyField(blank=True, related_name="+", to="extras.tag")),
            ],
            options={
                "verbose_name": "AI backend",
                "verbose_name_plural": "AI backends",
                "ordering": ["backend_key"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("enabled", True)),
                        fields=("enabled",),
                        name="ndi_inferencebackend_one_enabled",
                    )
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
