# Generated by Django 6.0.8 on 2026-09-12 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_job_notifications"),
        ("netbox_data_import", "0032_inference_timeout_floor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolutionProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("task_type", models.CharField(max_length=50)),
                ("field_key", models.TextField()),
                ("field_key_digest", models.CharField(blank=True, editable=False, max_length=64)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("source_evidence", models.JSONField()),
                ("resolved_device_id", models.PositiveBigIntegerField()),
                ("prompt_version", models.PositiveIntegerField()),
                ("response_schema_version", models.PositiveIntegerField()),
                ("candidate_snapshot", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("outcome", models.CharField(blank=True, default="", max_length=20)),
                ("selected_candidate_id", models.CharField(blank=True, default="", max_length=100)),
                ("selected_object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, default="")),
                ("backend_metadata", models.JSONField(blank=True, null=True)),
                ("response_diagnostic", models.JSONField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, default="", max_length=50)),
                ("decision", models.CharField(blank=True, default="", max_length=20)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_proposals",
                        to="netbox_data_import.importprofile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.objecttype"
                    ),
                ),
                (
                    "selected_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.objecttype",
                    ),
                ),
                (
                    "written_resolution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="netbox_data_import.terminationresolution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolution Proposal",
                "verbose_name_plural": "Resolution Proposals",
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("queued", "running"))),
                        fields=("profile", "task_type", "field_key_digest"),
                        name="ndi_resolutionproposal_one_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "completed"), models.Q(("outcome", ""), _negated=True)),
                            models.Q(models.Q(("status", "completed"), _negated=True), ("outcome", "")),
                            _connector="OR",
                        ),
                        name="ndi_resolutionproposal_completed_iff_outcome",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "failed"), models.Q(("failure_reason", ""), _negated=True)),
                            models.Q(models.Q(("status", "failed"), _negated=True), ("failure_reason", "")),
                            _connector="OR",
                        ),
                        name="ndi_resolutionproposal_failed_iff_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("outcome", "candidate"), _negated=True),
                            models.Q(
                                ("selected_object_id__isnull", False),
                                ("selected_object_type__isnull", False),
                                models.Q(("selected_candidate_id", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="ndi_resolutionproposal_candidate_has_selection",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("outcome", "no_match"), _negated=True),
                            models.Q(
                                ("selected_candidate_id", ""),
                                ("selected_object_id__isnull", True),
                                ("selected_object_type__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ndi_resolutionproposal_no_match_has_no_selection",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("decided_at__isnull", True), ("decision", "")),
                            models.Q(models.Q(("decision", ""), _negated=True), ("decided_at__isnull", False)),
                            _connector="OR",
                        ),
                        name="ndi_resolutionproposal_decision_group",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("decision", ""), ("status", "completed"), _connector="OR"),
                        name="ndi_resolutionproposal_decision_needs_completed",
                    ),
                ],
            },
        ),
    ]
