# Generated by Django 6.1 on 2026-09-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0033_resolutionproposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceDeviceResolution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("source_device_key", models.TextField()),
                ("source_device_key_digest", models.CharField(blank=True, editable=False, max_length=64)),
                ("selected_device_id", models.PositiveBigIntegerField()),
                ("selected_display_name", models.CharField(max_length=200)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_device_resolutions",
                        to="netbox_data_import.importprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trace Device Resolution",
                "verbose_name_plural": "Trace Device Resolutions",
                "ordering": ["profile", "source_device_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "source_device_key_digest"), name="ndi_tracedevresolution_profile_key"
                    )
                ],
            },
        ),
    ]
