# Generated by Django 6.1 on 2026-09-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # Hand-lowered from the generated pin: core.Job exists well before this node, and the
        # generator can only name what the generating machine has. See AGENTS.md.
        ("core", "0024_job_notifications"),
        ("netbox_data_import", "0035_retire_superseded_proposals"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolutionproposal",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolution_proposal",
                to="core.job",
            ),
        ),
    ]
