# Generated by Django 6.1 on 2026-09-22 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0036_resolutionproposal_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="CableSegmentOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("segment_key", models.CharField(max_length=200)),
                ("cable_type", models.CharField(blank=True, max_length=50, null=True)),
                ("cable_profile", models.CharField(blank=True, max_length=50, null=True)),
                ("source_trace_identity", models.TextField()),
                ("segment_index", models.PositiveIntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cable_segment_overrides",
                        to="netbox_data_import.importprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cable Segment Override",
                "verbose_name_plural": "Cable Segment Overrides",
                "ordering": ["profile", "segment_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "segment_key"), name="ndi_cablesegmentoverride_profile_segment"
                    )
                ],
            },
        ),
    ]
