# Generated by Django 6.1 on 2026-09-23 12:27

from django.db import migrations


def remove_job_plan_copies(apps, schema_editor):
    """Remove plan copies from import Jobs while leaving queued worker input intact."""
    schema_editor.execute(
        "UPDATE core_job SET data = data - 'accepted_plan' "
        "WHERE data->>'job_type' = 'netbox_data_import.import' AND data ? 'accepted_plan'"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0038_cable_tag_integrity"),
    ]

    operations = [
        # A removed plan cannot be reconstructed on rollback.
        migrations.RunPython(remove_job_plan_copies),
    ]
