# Generated by Django 6.1 on 2026-09-29 16:28

from django.db import migrations

# The rows move between main-only tables and extras_taggeditem, so a branch migrate must not run this again.
fake_on_branch = True

APP_LABEL = "netbox_data_import"
TAGGED_MODELS = ("importprofile", "inferencebackend")


def _tag_links(apps, model_name):
    """Return the historical through model of one tags many-to-many field."""
    return apps.get_model(APP_LABEL, model_name).tags.through


def move_tags_to_tagged_items(apps, schema_editor):
    """Move every tags through-table row into NetBox's standard tag assignment table."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    TaggedItem = apps.get_model("extras", "TaggedItem")
    for model_name in TAGGED_MODELS:
        rows = _tag_links(apps, model_name).objects.all()
        links = list(rows.values_list(f"{model_name}_id", "tag_id"))
        if not links:
            continue
        content_type = ContentType.objects.get(app_label=APP_LABEL, model=model_name)
        TaggedItem.objects.bulk_create(
            TaggedItem(content_type=content_type, object_id=object_id, tag_id=tag_id) for object_id, tag_id in links
        )
        # Each assignment lives in one table only, so a rollback of this migration alone does not duplicate it.
        rows.delete()


def move_tagged_items_to_tags(apps, schema_editor):
    """Copy the tag assignments of existing objects back into their through tables, and drop the rest."""
    TaggedItem = apps.get_model("extras", "TaggedItem")
    for model_name in TAGGED_MODELS:
        links = _tag_links(apps, model_name)
        items = TaggedItem.objects.filter(content_type__app_label=APP_LABEL, content_type__model=model_name)
        existing = items.filter(object_id__in=apps.get_model(APP_LABEL, model_name).objects.values("pk"))
        links.objects.bulk_create(
            links(**{f"{model_name}_id": object_id, "tag_id": tag_id})
            for object_id, tag_id in existing.values_list("object_id", "tag_id")
        )
        items.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0039_remove_job_plan_copies"),
    ]

    operations = [
        migrations.RunPython(move_tags_to_tagged_items, move_tagged_items_to_tags),
    ]
