# Generated by Django 6.1 on 2026-09-29 16:28

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # No extras node of its own: 0020 already pins `extras.0140`, which this descends from.
        ("netbox_data_import", "0040_move_tags_to_tagged_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importprofile",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="inferencebackend",
            name="tags",
        ),
        migrations.AddField(
            model_name="importprofile",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="inferencebackend",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
    ]
