# Generated by Django 6.0.8 on 2026-10-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0041_remove_importprofile_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceLocationResolution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("source_location_key", models.TextField()),
                ("source_location_key_digest", models.CharField(blank=True, editable=False, max_length=64)),
                ("selected_location_id", models.PositiveBigIntegerField()),
                ("selected_display_name", models.CharField(max_length=200)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_location_resolutions",
                        to="netbox_data_import.importprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trace Location Resolution",
                "verbose_name_plural": "Trace Location Resolutions",
                "ordering": ["profile", "source_location_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "source_location_key_digest"), name="ndi_tracelocresolution_profile_key"
                    )
                ],
            },
        ),
    ]
