# Generated by Django 6.1 on 2026-10-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0042_tracelocationresolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminationresolution",
            name="source_cards",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="terminationresolution",
            name="source_device",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="terminationresolution",
            name="source_port",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tracedeviceresolution",
            name="source_device_label",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tracelocationresolution",
            name="source_location_path",
            field=models.TextField(blank=True, default=""),
        ),
    ]
