# Generated by Django 6.0.8 on 2026-10-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0043_decision_source_spelling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cableimportsource",
            name="segment_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
