# Generated by Django 6.1 on 2026-10-01 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_import", "0045_rekey_name_identities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviewCoordinator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("session_binding", models.CharField(max_length=64, unique=True)),
                ("preview_token", models.CharField(max_length=64)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("state", models.CharField(default="empty", max_length=16)),
                ("profile_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("source_document_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("plan", models.JSONField(blank=True, null=True)),
                ("job_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Preview Coordinator",
                "verbose_name_plural": "Preview Coordinators",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)), name="ndi_previewcoordinator_revision"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["empty", "ready", "sync_pending", "submitted", "expired"])),
                        name="ndi_previewcoordinator_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state__in", ["ready", "submitted", "sync_pending"]), _negated=True),
                            models.Q(
                                ("profile_id__isnull", False),
                                ("source_document_id__isnull", False),
                                ("plan__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ndi_previewcoordinator_active_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["ready", "submitted", "sync_pending"]),
                            models.Q(
                                ("profile_id__isnull", True),
                                ("source_document_id__isnull", True),
                                ("plan__isnull", True),
                                ("job_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ndi_previewcoordinator_inactive_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("job_id__isnull", False), ("state__in", ["submitted", "sync_pending"])),
                            models.Q(
                                models.Q(("state__in", ["submitted", "sync_pending"]), _negated=True),
                                ("job_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ndi_previewcoordinator_job",
                    ),
                ],
            },
        ),
    ]
