# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Marcin Zieba <marcinpsk@gmail.com>
"""Write the compatibility metadata from the version the plugin enforces and the version CI tests.

`netbox-plugin.yaml` feeds the NetBox Labs plugin catalog and `COMPATIBILITY.md` states the same
matrix for readers. Nothing updated either one for 14 releases, because semantic-release bumps only
`pyproject.toml` and `__init__.py`. Both files are generated here instead: the floor is the
`min_version` NetBox enforces at load, and the ceiling is the newest NetBox the test matrix runs.
The release build command and a pre-commit hook run this.
"""

from __future__ import annotations

import ast
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
PLUGIN_CONFIG = ROOT / "netbox_data_import" / "__init__.py"
TEST_WORKFLOW = ROOT / ".github" / "workflows" / "test.yaml"
MATRIX_NETBOX = re.compile(r'^\s*-?\s*netbox-version:\s*"?v?([0-9]+(?:\.[0-9]+)*)"?\s*$', re.MULTILINE)

# The catalog file states the format it follows here, not the plugin version.
SCHEMA_VERSION = "0.1"
PACKAGE_NAME = "netbox-data-import"

# Each release below starts a supported range that holds until the release above it. Add a row when
# the range changes. Both rows are read off the tags: 1.0.0 enforced 4.2.0 with CI on v4.3.7, and
# 1.5.0 raised the floor to 4.6.0 with CI on v4.6.7.
RANGE_HISTORY = [
    ("1.5.0", "4.6.0", "4.6.7"),
    ("1.0.0", "4.2.0", "4.3.7"),
]

MD_COLUMNS = ("Release", "Minimum NetBox Version", "Maximum NetBox Version")
GENERATED = "Generated by scripts/gen_compatibility.py. Do not edit."


def as_tuple(version: str) -> tuple[int, ...]:
    """Return a comparable form of a dotted version."""
    return tuple(int(part) for part in version.split("."))


def read_plugin_config() -> tuple[str, str]:
    """Return `__version__` and the config's `min_version`, read without importing NetBox."""
    found: dict[str, str] = {}
    for node in ast.walk(ast.parse(PLUGIN_CONFIG.read_text())):
        if not isinstance(node, ast.Assign) or not isinstance(node.value, ast.Constant):
            continue
        if not isinstance(node.value.value, str):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id in {"__version__", "min_version"}:
                found[target.id] = node.value.value
    missing = {"__version__", "min_version"} - found.keys()
    if missing:
        raise SystemExit(f"gen-compatibility: {PLUGIN_CONFIG.name} defines no {', '.join(sorted(missing))}")
    return found["__version__"], found["min_version"]


def newest_tested_netbox() -> str:
    """Return the newest NetBox release the test matrix runs, which is the highest verified version."""
    tested = MATRIX_NETBOX.findall(TEST_WORKFLOW.read_text())
    if not tested:
        raise SystemExit(f"gen-compatibility: {TEST_WORKFLOW.name} lists no netbox-version, so the scan is broken")
    return max(tested, key=as_tuple)


def compatibility_rows() -> list[tuple[str, str, str]]:
    """Return the catalog rows, newest first, with the current release on top."""
    version, min_version = read_plugin_config()
    netbox_max = newest_tested_netbox()
    if as_tuple(netbox_max) < as_tuple(min_version):
        raise SystemExit(
            f"gen-compatibility: the test matrix tops out at NetBox {netbox_max}, below the {min_version} "
            f"the plugin requires at load. Raise the matrix or lower min_version."
        )
    newest_release, newest_min, newest_max = RANGE_HISTORY[0]
    if (min_version, netbox_max) == (newest_min, newest_max):
        return list(RANGE_HISTORY)
    return [(version, min_version, netbox_max), *RANGE_HISTORY]


def render_yaml(rows: list[tuple[str, str, str]]) -> str:
    """Render the catalog file the NetBox Labs plugin catalog reads."""
    lines = [
        "# Format: https://github.com/netbox-community/netbox/wiki/Plugin-Certification-Program",
        "# To register in the NetBox Labs plugin catalog, email: plugincatalog@netboxlabs.com",
        "# Include: plugin name, email, GitHub repo, PyPI link, config name (netbox_data_import)",
        f"# {GENERATED}",
        f"version: {SCHEMA_VERSION}",
        f"package_name: {PACKAGE_NAME}",
        "compatibility:",
    ]
    for release, netbox_min, netbox_max in rows:
        lines += [
            f"  - release: {release}",
            f"    netbox_min: {netbox_min}",
            f"    netbox_max: {netbox_max}",
        ]
    return "\n".join(lines) + "\n"


def render_markdown(rows: list[tuple[str, str, str]]) -> str:
    """Render the same matrix for readers, padded to the column headings."""
    widths = [len(column) for column in MD_COLUMNS]

    def row(cells: tuple[str, ...], fill: str = " ") -> str:
        return "| " + " | ".join(cell.ljust(width, fill) for cell, width in zip(cells, widths)) + " |"

    lines = [
        "# Compatibility Matrix",
        "",
        f"<!-- {GENERATED} -->",
        "",
        "The minimum is the NetBox version the plugin requires at load. The maximum is the newest",
        "NetBox version the test matrix runs. Each release starts a range that holds until the",
        "release above it.",
        "",
        row(MD_COLUMNS),
        row(("-", "-", "-"), fill="-"),
        *(row(cells) for cells in rows),
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write both files and name the ones that changed.

    A rewrite is the point of the hook, not a failure, so it exits 0: pre-commit fails the run
    itself when a hook modifies a file, and the release build command must abort only on a
    metadata it cannot generate.
    """
    rows = compatibility_rows()
    written = []
    for path, text in (
        (ROOT / "netbox-plugin.yaml", render_yaml(rows)),
        (ROOT / "COMPATIBILITY.md", render_markdown(rows)),
    ):
        if path.read_text() != text:
            path.write_text(text)
            written.append(path.name)
    if written:
        print(f"gen-compatibility: rewrote {', '.join(written)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
